### ISSUE TITLE
Should propIf instantiate stuff only when it evaluates to true?

### ISSUE THREAD

**Issue by giuseppeg** [kentcdodds/webpack-config-utils#1]
Hi @kentcdodds these utils are great!
I first saw them in your egghead course and I have question.

At the moment when one does
```javascript
ifProduction(
  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: '"production"',
    },
  })
)
```
an instance of `webpack.DefinePlugin` is created no matter what is the value of `envValue`.

Not a big deal probably but I was wondering if it wouldn't be better to have the tool `eval` some code or pass the plugin + options.

```javascript
ifProduction(`
  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: '"production"',
    },
  })
`)
```
or

```javascript
ifProduction(
  webpack.DefinePlugin,
  {
    'process.env': {
      NODE_ENV: '"production"',
    },
  }
)
```

**Comment by kentcdodds** [comment]
Hi @giuseppeg!
I'm glad that you've found my little util library :)

I've considered what you're talking about because it is technically wasteful, but I've not had any real issues with it so I haven't really cared to fix the perceived problem.

I don't think that `eval` would be a great solution because you could wind up with some interesting interpolation issues. The goal is to make webpack's API simpler, not more complex ;-)

For your second example, I'm still not certain that's any simpler.

One thing that I've thought about is:

```javascript
ifProdFn(() => new webpack.DefinePlugin({'process.env': {NODE_ENV: '"production"'}}))
```

Where `ifProdFn` would actually call the function if it evaluates to `true`. I worry that this would unnecessarily complicate things, but I'm curious to hear what you think.

**Comment by giuseppeg** [comment]
I didn't think about the anonymous function, good idea!
Anyway I agree with everything you said ;)

An alternative API could be:

```javascript
[
  ifProduction() && new webpack.DefinePlugin({'process.env': {NODE_ENV: '"production"'}}),
  ifDevelopment() && new somethingElse()
].filter(Boolean)
```

but then `ifEnviroment` would be just a shortcut for `process.env.NODE_ENV == 'environment'`.

Feel free to close the issue if you want and thanks for the quick answer!

**Comment by kentcdodds** [comment]
Yeah, I think we'll just say here that it's not enough of a problem to justify adding complexity to the tool. Thanks for bringing it up though!

If you'd like, you could add this to the `wont do` in [the ROADMAP.md](https://github.com/kentcdodds/webpack-config-utils/blob/master/other/ROADMAP.md) 👍
